#! /bin/bash

cat <<HEAD
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title></title>
  <style type="text/css">
    code{white-space: pre;}
    a{text-decoration: none;}
    table{border-spacing: 5px 0;background-color: #eee;}
    h2{font-size: 14px;}
    .shade{background-color: #eee;max-width: 42em;}
  </style>
HEAD

cat pandoc.css

cat <<BODY
</head>
<body>

<h1 id="mlhub-pre-built-model-catalogue">MLHub Currated Packages</h1>

<p>The MLHub repository hosts the following currated pre-built machine
learning models.  Try them out and let us know if you have any issues.
They are easily and quickly installed and demonstrated.  Feedback is
welcome through <a
href="https://github.com/mlhubber/mlmodels">github</a>.  Visit <a
href="https://mlhub.ai">MLHub.ai</a> for details.</p>

<p>Anyone can create a MLHub package simply by including a
<i>MLHUB.yaml</i> file in their github repository. The models listed
here are currated in by MLHub administrators. If you find any issues
do be sure to report them.</p>

<h1 id="mlhub-pre-built-model-catalogue">Catalogue</h1>
<br>
<table>
<thead>
<tr class="header">
<th align="left">Name</th>
<th align="left">Version</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
BODY

cat Packages.yaml |\
  egrep '^ +(name|url)' |\
  paste -s -d' \n' |\
  perl -pe 's|^ +name *: ||' |\
  perl -pe 's| +url *: *| |' > Packages.url

${HOME}/.local/bin/ml available |\
  egrep '^([[:alpha:]]|[[:digit:]]|_)+ +[[:digit:]]' > Packages.tbl

join Packages.url Packages.tbl |\
   perl -pe 's|^(.)([^ ]*) +([^ ]*) +([^ ]*) +(.*?) *$|
<tr>
<td align="left">
  <a href="$3">$1$2</a>
</td>
<td align="left">$4</td>
<td align="left">$5</td>
</tr>|'
  
#  sed 's|^|<tr>\n<td align="left"><a href="https://mlhub.ai/pool/main/">|' |\
#  sed 's| *: |</a></td>\n<td>|' |\
#  perl -pe 's| *: |

cat <<KWD

</tbody>
</table>

<h1>Showcase</h1>

<h4>Visualisation</h4>

Visual presetnation of data is crucial for understanding data and
sharing the data story with others. <a
href="https://github.com/gjwgit/animate">Animations</a> can be quite
effective in telling the story over time. The basic visualisations
include the <a href="https://github.com/gjwgit/barchart">barchart</a>
and the <a href="https://github.com/gjwgit/scatter">scatter</a>
plot. A more informative scatter plot is the <a
href="https://github.com/gjwgit/beeswarm">beeswarm</a>
plot. Visualisations are effectively used in all kinds of reports as
in this study of  <a
href="https://github.com/gjwgit/ports">Australian sea ports</a>.

<h4>Prediction</h4>

<a href="https://github.com/gjwgit/rain">rain</a> &mdash;
<a href="https://github.com/gjwgit/audit">audit</a> &mdash;
<a href="https://github.com/gjwgit/iris">iris</a> &mdash;
<a href="https://github.com/gjwgit/movies">movies</a> &mdash;
<a href="https://gitlab.com/kayontoga/ocsvm">ocsvm</a>

<H4>Computer Vision</h4>

<a href="https://gitlab.com/kayontoga/cars">cars</a> &mdash;
<a href="https://github.com/mlhubber/objects">objects</a> &mdash;
<a href="https://github.com/gjwgit/opencv">opencv</a> &mdash;
<a href="https://github.com/mlhubber/colorize">colorize</a> &mdash;
<a href="https://github.com/simonzhaoms/facedetect">facedetect</a>

<h4>Azure Cloud AI</h4>

<a href="https://github.com/gjwgit/azcv">azcv</a> &mdash;
<a href="https://github.com/gjwgit/aztext">aztext</a> &mdash;
<a href="https://github.com/gjwgit/aztranslate">aztranslate</a> &mdash;
<a href="https://github.com/gjwgit/azface">azface</a> &mdash;
<a href="https://github.com/gjwgit/azspeech">azspeech</a> &mdash;
<a href="https://github.com/gjwgit/azanomaly">azanomaly</a> &mdash;
<a href="https://github.com/gjwgit/azlang">azlang</a>

<h1>Index</h1>
KWD

# Add Keywords

Rscript kwdidx.R

cat <<EOF

</body>
EOF


